import requests

DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1388114306390032445/WEfgjR0sesNCffYZ0LLlLKnqzt-p9mXvRZa18gEYuJJ5iVaTDTUmEBtb7ICx6oJP99DL"

def send_hi():
    data = {"content": "hi"}
    response = requests.post(DISCORD_WEBHOOK_URL, json=data)
    if response.status_code == 204:
        print("Sent 'hi' to Discord!")
    else:
        print(f"Error: {response.status_code} {response.text}")

def listen_for_meow():
    print("Type a message. If you type 'meow', I’ll say 'hi' on Discord!")
    while True:
        msg = input("> ").strip().lower()
        if msg == "meow":
            send_hi()

if __name__ == "__main__":
    listen_for_meow()
